name: san
recipe: drupal8
config:
  php:  '7.3'
  webroot: .
  xdebug: true
services:
  pma:
    type: phpmyadmin
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
tooling:
    drush:
        cmd: vendor/drush/drush/drush
    drupal:
        cmd: vendor/drupal/console/bin/drupal
