<?php

/**
 * @file
 * Contains sah_modifications.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sah_modifications_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sah_modifications module.
    case 'help.page.sah_modifications':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom modifications for SAH') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_mail().
 */
function sah_modifications_mail($key, &$message, $params) {
  switch ($key) {
    case 'quote_notification_user':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['salutation'] = $params['salutation'];
      $message['data'] = $params['data'];
      break;
  }
}

/**
 * implements hook_mail_alter()
 */
function sah_modifications_mail_alter(&$message) {
  if($message['id'] == 'user_register_no_approval_required' || $message['id'] == 'user_password_reset') {
    $account = $message['params']['account'];
    $data = [];
    $data['username'] = $account->name->value;
    $data['url'] = user_pass_reset_url($account);
    $message['data'] = $data;
  }
}
